# Copyright 2025-2026 Hanlian Lu. SPDX-License-Identifier: Apache-2.0
"""Corpus Administration use case and caller contracts."""

from dlightrag.engine.ai.telemetry import safe_log_text
from dlightrag.engine.public_http import validate_public_web_url
from dlightrag.engine.rag.corpus.contracts import SourceType, VisualAssetSize
from dlightrag.engine.rag.corpus.sources.source_contract import safe_source_filename
from dlightrag.engine.rag.workspace.workspaces import (
    normalize_workspace,
    normalize_workspace_ids,
)

from .errors import (
    LocalDownloadTarget,
    MetadataValidationError,
    RedirectDownloadTarget,
    SourceDownloadInvalidError,
    SourceDownloadNotFoundError,
    SourceDownloadTarget,
    SourceDownloadUnavailableError,
    UnsafeUploadNameError,
    UploadTooLargeError,
)
from .file_panel import (
    FILE_PANEL_PAGE_DEFAULT_LIMIT,
    FILE_PANEL_PAGE_MAX_LIMIT,
    FailedFileRow,
    FailedFileRowPage,
    FilePanelCursor,
    FilePanelCursorCodec,
    FilePanelCursorError,
    FilePanelPageRequest,
    FilePanelRowPage,
    ProcessedFileRow,
    public_failure_diagnostic,
)
from .metadata_search import (
    METADATA_SEARCH_PAGE_DEFAULT_LIMIT,
    METADATA_SEARCH_PAGE_MAX_LIMIT,
    MetadataMatchRowPage,
    MetadataSearchCursor,
    MetadataSearchCursorCodec,
    MetadataSearchCursorError,
    MetadataSearchFilenameMode,
    MetadataSearchPage,
    MetadataSearchPageRequest,
)
from .mutations import (
    CorpusMutationAction,
    CorpusMutationExecutor,
    CorpusMutationService,
    RetrySelector,
    StagedCorpusSource,
)
from .service import (
    CorpusAdmin,
    CorpusAdminSettings,
    FailedFileSnapshot,
    FilePanelSnapshot,
    FilePanelStore,
    IngestSpec,
    MetadataSearchStore,
    SourceDownloadFactory,
    SourceDownloadPreparer,
    ingest_kwargs_from_spec,
    ingest_spec_from_payload,
    managed_local_ingest_documents,
    managed_local_ingest_path,
    safe_upload_basename,
    validate_workspace_name,
)
from .workspace_catalog import (
    WORKSPACE_CATALOG_PAGE_DEFAULT_LIMIT,
    WORKSPACE_CATALOG_PAGE_MAX_LIMIT,
    WorkspaceCatalogCursor,
    WorkspaceCatalogCursorCodec,
    WorkspaceCatalogCursorError,
    WorkspaceCatalogPage,
    WorkspaceCatalogPageRequest,
    WorkspaceCatalogRowPage,
)

__all__ = [
    "CorpusAdmin",
    "CorpusAdminSettings",
    "CorpusMutationAction",
    "CorpusMutationExecutor",
    "CorpusMutationService",
    "FILE_PANEL_PAGE_DEFAULT_LIMIT",
    "FILE_PANEL_PAGE_MAX_LIMIT",
    "FailedFileRow",
    "FailedFileRowPage",
    "FailedFileSnapshot",
    "FilePanelCursor",
    "FilePanelCursorCodec",
    "FilePanelCursorError",
    "FilePanelPageRequest",
    "FilePanelRowPage",
    "FilePanelSnapshot",
    "FilePanelStore",
    "IngestSpec",
    "LocalDownloadTarget",
    "MetadataValidationError",
    "MetadataMatchRowPage",
    "MetadataSearchCursor",
    "MetadataSearchCursorCodec",
    "MetadataSearchCursorError",
    "MetadataSearchFilenameMode",
    "MetadataSearchPage",
    "MetadataSearchPageRequest",
    "MetadataSearchStore",
    "METADATA_SEARCH_PAGE_DEFAULT_LIMIT",
    "METADATA_SEARCH_PAGE_MAX_LIMIT",
    "ProcessedFileRow",
    "public_failure_diagnostic",
    "RedirectDownloadTarget",
    "RetrySelector",
    "StagedCorpusSource",
    "SourceDownloadFactory",
    "SourceDownloadInvalidError",
    "SourceDownloadNotFoundError",
    "SourceDownloadPreparer",
    "SourceDownloadTarget",
    "SourceDownloadUnavailableError",
    "UnsafeUploadNameError",
    "UploadTooLargeError",
    "WORKSPACE_CATALOG_PAGE_DEFAULT_LIMIT",
    "WORKSPACE_CATALOG_PAGE_MAX_LIMIT",
    "WorkspaceCatalogCursor",
    "WorkspaceCatalogCursorCodec",
    "WorkspaceCatalogCursorError",
    "WorkspaceCatalogPage",
    "WorkspaceCatalogPageRequest",
    "WorkspaceCatalogRowPage",
    "ingest_kwargs_from_spec",
    "ingest_spec_from_payload",
    "managed_local_ingest_documents",
    "managed_local_ingest_path",
    "normalize_workspace",
    "normalize_workspace_ids",
    "safe_log_text",
    "safe_source_filename",
    "safe_upload_basename",
    "SourceType",
    "validate_public_web_url",
    "validate_workspace_name",
    "VisualAssetSize",
]
